### ISSUE TITLE
此项目不在继续维护了吗？

### ISSUE THREAD

**Issue by zgr0629** [WeijuNB/PyF5#14]
Mac里getf5网站上下载到的app不起作用，这里源码编译也有问题
app下来之后可以启动，添加工程目录进去之后，sublime端更新html文件，浏览器这边没有正确刷新。

在这里下载的源码按照安装方法发现有问题

✘  ~/Downloads/PyF5-master  sudo easy_install pyf5
Processing pyf5
error: Couldn't find a setup script in /Users/zgr0629/Downloads/PyF5-master/pyf5

直接跑f5.py也有问题
✘  ~/Downloads/PyF5-master  python f5.py
Traceback (most recent call last):
  File "f5.py", line 5, in <module>
    from tornado import ioloop
ImportError: No module named tornado

我从来没有弄过Python，不知道是不是有依赖包之类的没有装呢？

环境
osx 10.11.3
Python 2.7.11

**Comment by luwenjin** [comment]
是的，暂时不维护了。
不过你还是可以按照『直接跑』的方式来运行，如果遇到 
ImportError: No module named XXXXX
的提示，就执行sudo easy_install XXXXX来解决
