### ISSUE TITLE
支持sass编译

### ISSUE THREAD

**Issue by luwenjin** [WeijuNB/PyF5#2]

**Comment by ksky521** [comment]
请支持sass编译，基于compass的config.rb文件

**Comment by luwenjin** [comment]
尝试用node-sass项目来实现，不过问题比较多：
1. 不支持.sass文件，只支持.scss文件
2. 不支持 darken 这类函数，而且不会报错

所以要暂缓对sass编译的支持了，
将来也许要把ruby也打包进来，这样就可以支持sass了
