### ISSUE TITLE
4.x的项目列表页能否改进一下.

### ISSUE THREAD

**Issue by NMTuan** [WeijuNB/PyF5#6]
平时做前端工作需要ie6~8的虚拟机进行兼容性测试.
原来在3.x下访问项目列表很容易.键入ip就是了.能直接显示项目列表.跟本机用一样.
现在换到4.x下.就没那么容易测试了..
4.x早期的时候.在虚拟机中键入ip.项目列表页面只显示添加项目的input.
换到4.3后.虚拟机浏览项目列表时.直接报错.ie无法打开站点..
不过直接键入文件名.还是可以访问的.

环境是win7x64.sp1
虚拟机是virtualbox
网卡模式是 网络地址转换(NAT) 网段10.0.2.2

**Comment by luwenjin** [comment]
已在 2caede3bf897fec0e8391cd34ce0ecb2d504deda 中修改，并且在IE8下测试通过，没有试过IE6/7，应该问题不大，等sass的issue解决了以后一起打包发布
如果急着用，用最新的“_”目录替换掉本地的即可

**Comment by luwenjin** [comment]
已发
