### ISSUE TITLE
建议：能不能给【F5功能】加上一个开关？

### ISSUE THREAD

**Issue by donson** [WeijuNB/PyF5#9]
1. 给【F5功能】加上一个开关
   
   > 当关了这个功能后，就纯当一个静态服务器来用，我喜欢PyF5自己生成二维码功能。
2. 改变断开链接的方式
   
   > 现在断开链接的方式是简单粗暴的`alert`，这样在开发过程中很不舒服，我建议不提示，或者只在服务端提示。

**Comment by luwenjin** [comment]
针对这两个建议，我想更详细地了解一下
1、什么时候F5的自动刷新功能会给你带来困扰？
2、断开连接的一般也只有关闭F5的时候会提示一次，或者F5程序问题，这个偶尔出现，应该问题不大；相反如果莫名其妙不刷新了，而有没有提示的话，可能会是一个更大的问题。所以我们采用alert这话简单粗暴方式来提示这个。你这边是不是会频繁提醒，所以觉得很烦？

**Comment by hepochen** [comment]
第二个问题，当浏览器多开几个Tab，有些时候是有点烦的。

文进，试试这个JS库 http://sofish.github.io/essage/ ？集成的成本跟alert差不多。

---

Designing with FarBox now.

Mobile: +86-13588132569
Gtalk: hepochen@gmail.com
Email: hepo@ued.com.cn

**Comment by luwenjin** [comment]
海波这库不错，我先记着

**Comment by donson** [comment]
我的第一个困扰应该是来自第二点`alert`的：

我现在尝试开发手机网站，三台手机通过wifi链接，可能公司wifi信号不好，久不久会断一下（手机会重新联网），在这种情况下，我手动刷新一下就好，弹`alert`很不舒服，而F5的二维码功能太方便了，又不舍得换普通的静态服务器。

所以才会想到，是否能做个【F5功能】的开关，或者改进断开链接的提示方式。

**Comment by luwenjin** [comment]
恩，那我理解了，我可能会采用新的通知断线的方式。暂时的话，你可以手动编辑一下assets目录下面的reloader.js文件，搜索alert就可以看到在哪里提示的。

**Comment by donson** [comment]
嗯，已经改好了。
